Repository TenzDelek/DearDiary, pull requests merged in 2024-10, with the labels that each got.

#24 Feature/add husky Pre-commit
  package-lock.json
  package.json
Labels: gssoc-ext, hacktoberfest-accepted, Level 2

#25 Added Navbar
  src/app/daily-quote/page.js
  src/app/layout.jsx
  src/app/notes/page.js
  src/components/Navbar.js
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, Level 1

#27 Feat/prisma supabase setup
  lib/db.ts
  package-lock.json
  package.json
  prisma/schema.prisma
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, Level 2

#53 Created CodeofConduct.md
  CodeofConduct.md
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, Level 1, Docs

#60 About page
  package-lock.json
  package.json
  src/app/about/page.jsx
  src/components/Navbar.js
  src/components/ui/label.jsx
  tsconfig.json
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, Level 3

#44 set up supabase/prima and create guestbook
  .env.example
  package-lock.json
  package.json
  prisma/schema.prisma
  src/app/api/auth/route.js
  src/app/api/guestbook/entries/route.js
  src/app/api/guestbook/route.js
  src/app/guestbook/form.jsx
  src/app/guestbook/layout.jsx
  src/app/guestbook/page.jsx
  src/app/sign-up/[[...sign-up]]/page.jsx
  src/components/Navbar.js
  src/lib/db.js
  tsconfig.json
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, Level 3

#50 added theme toggler
  package-lock.json
  src/app/layout.jsx
  src/app/notes/page.js
  src/components/ThemeToggle.jsx
  src/context/ThemeProvider.js
  tailwind.config.js
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, Level 3, Priority

#78 improved navbar interaction
  src/components/Navbar.js
Labels: enhancement, good first issue, gssoc-ext, hacktoberfest-accepted, Level 1

#79 Fixed: Getting 404 in login page route
  src/app/(auth)/sign-in/[[...sign-in]]/page.jsx
  src/app/(auth)/sign-up/[[...sign-up]]/page.jsx
  src/app/page.jsx
  src/middleware.js
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, Level 2

#69 bugfix/correct-favicon-location
  public/favicon/site.webmanifest
  src/app/layout.jsx
Labels: enhancement, good first issue, gssoc-ext, hacktoberfest-accepted, Level 1

#152 Added copy confirmation and loading state
  src/app/daily-quote/page.jsx
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, Level 2

#167 Review Modal Updated
  src/components/ReviewModal.jsx
Labels: enhancement, good first issue, gssoc-ext, hacktoberfest-accepted, Level 1

#176 chore: remove hover
  src/app/about/page.jsx
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, Level 1
